### ISSUE TITLE
Kubos

### ISSUE THREAD

**Issue by karimnorouzi** [marko-knoebl/slides#8]
Hello Marko,
I have a question about Kubos, the program you wrote a few years ago. I hope I am correct in assuming that you wrote kubos.
There is a question regarding the deletion of selected shapes  in Kubos in a fourom. In that question, you are using OCAF as the underlying Document management system. However, when you released Kubos, there is no use of OCAF. Why you did not use  OCAF and switched to something else ? Or did I miss OCAF related stuff when looking through the code ?
thanks.

**Comment by marko-knoebl** [comment]
Hey!

So I originally wrote Kubos as a desktop application using OCAF - see the code here: https://sourceforge.net/p/kubos/wiki/Home/

Later I started a new project for implementing a web-based version which I put here on GitHub. That one doesn't use OCAF.

I hope that cleared up things.
